# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9280a1f0f0fa4d97f0e543cd93548d3ff4e98f388f13dc97f1d305d1f8558a1bea56303b187d71458360718d16e06fd67d77962e359ec9f7d582b690a91e7ad

test:
  secret_key_base: 8a21aafb1e385f04de753626a658ecb1f4a158a870e5385b0960885eaf72f28e99e8401dfe90b4e82fca647d99bb69702760c3ee3002d7790637bf7f452b9be7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
